id: PB0F464EB
initial_creation_type: input
source_metadata:
  title: Words of the Buddha
  language: zh
  description: 'A selection of works by the Buddha himself, many of which feature
    in the Kangyur (bka'' ''gyur), the Tibetan canonical collection of the Buddha''s
    Word:'
  volume:
    8b4bc390f1c541f9a6081a0b8213d238:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Auspiciousness
    88f7ba3038444cffad55a322bb1fc9f9:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī
    474d4e4583a743d7a87c9bb5728e1ae0:
      title: The Dhāraṇī of Glorious Vajraṇakhī
      parent: Dhāraṇī
    89d6756a95a648ffa5365eaf4b5f0869:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Dhāraṇī
    9da617a47be44bc2934c2ac63fb04b09:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Dhāraṇī
    519d3d7838234fdea352274f789b6398:
      title: The Noble Essence of Dependent Origination
      parent: Dhāraṇī
    a2c65fc810684dadb0d4643d78e0c948:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Dhāraṇī
    9541a42b05ad4fe48e18d08a6437b10b:
      title: The Noble Mārīcī Dhāraṇī
      parent: Dhāraṇī
    61d769bb3e4046698b84f13e0af7775a:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Dhāraṇī
    3955e0102ba44a5b818cc4df6c6e9ea4:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    a2f1cf5323914d6b962f4d435b5b1181:
      title: 'The Clarifying Light: A Prophecy of the Future'
      parent: Prophecy
    099ec0c7d9da4eb0a9b531cfe2e0e8dd:
      title: The Song of the Vajra
      parent: Songs
    16c7dd01d57a4a1097b78b83876bc437:
      title: Maitreya's Aspiration
      parent: Sūtra
    7f8bd5d723c145f292d7aa9233a5dde7:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtra
    8d1665b3db834b68b10e534cd7cd3d8f:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtra
    b625123fc6664bb2b1b6c38707fac0a0:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtra
    f3b00db9065d488796e0ce67bdf0c525:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtra
    8e6c9f87089840c3b4389b399fb75e37:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Sūtra
    19721d2e79b1406ba517b98c5b040997:
      title: The Noble Sūtra of Recalling the Three Jewels
      parent: Sūtra
    4f29bdf5c99748ceb7c5aa8bf4137e56:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Sūtra
    f5c094aaa5dd4994ab350ad087b95f81:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtra
    4f73d837bfbb4c05978201579f47a4d4:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    88e7d12a129e46208b373d87ca6e164f:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    6b52c654bf2e46b79de55dea55e7fe3d:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Tantra
    9f50a161dd514b18bb02e6ff12e9f6fe:
      title: The Lament of Rudra
      parent: Tantra
    c8723ee53f484be7aa4cc32e856d6b51:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tantra
    7705a68451ca470bb8e4aa70d20d7c91:
      title: The Twenty-Eight Commitments
      parent: Tantra
    9c3cf24b35a0483896f67792005373a4:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Tantra
    c66fe9bd71394ac2b56e88f2b23347db:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Tantra
created_at: '2022-03-01T02:07:32.766643'
last_modified_at: '2022-03-01T02:07:32.766646'
